feat: add input variable auto_pause_delay_in_minutes
equinor/terraform-azurerm-sql pull request #162
Opened 2024-12-19 14:31 UTC by chbul

Closes https://github.com/equinor/terraform-baseline/issues/197

2024-12-19 15:10 UTC, chbul commented
Improvement suggestion: `auto_pause_delay_in_minutes` is only settable on serverless databases. Add variable validation rule that prevents non-serverless SKU's.

2024-12-20 11:52 UTC, hknutsen requested changes

2024-12-20 11:52 UTC, hknutsen commented on modules/database/variables.tf
> +    condition     = contains(["GP_S_Gen5_1", "GP_S_Gen5_2", "GP_S_Gen5_4", "GP_S_Gen5_6", "GP_S_Gen5_8"], var.auto_pause_delay_in_minutes)
Won't this check for `auto_pause_delay_in_minutes == "GP_S_Gen5_1"` and so on?

2024-12-20 11:52 UTC, hknutsen commented on modules/database/variables.tf
> +  description = "Time in minutes after which database is automatically paused. Only settable for Serverless databases."
Update description to match usual phrasing:

```suggestion
  description = "Time in minutes after which this SQL database is automatically paused. Value must be greater than 0 if using a SKU in the serverless compute tier."
```

2024-12-20 11:53 UTC, hknutsen commented on modules/database/variables.tf
> +    condition     = contains(["GP_S_Gen5_1", "GP_S_Gen5_2", "GP_S_Gen5_4", "GP_S_Gen5_6", "GP_S_Gen5_8"], var.auto_pause_delay_in_minutes)
Might want to remove this validation rule altogether, since it might be optimistic to maintain a list of available SKUs.

2024-12-20 12:17 UTC, hknutsen approved these changes

2024-12-20 12:18 UTC, merged