feat(database): configure minimal capacity
equinor/terraform-azurerm-sql pull request #163
Opened 2024-12-19 14:46 UTC by chbul

Closes https://github.com/equinor/terraform-baseline/issues/196

2024-12-19 15:09 UTC, chbul commented
Improvement suggestion: `min_capacity` is only settable on serverless databases. Add variable validation rule that prevents non-serverless SKU's.

2024-12-20 11:53 UTC, hknutsen requested changes

2024-12-20 11:53 UTC, hknutsen commented on modules/database/variables.tf
> +  description = "Minimal capacity that database will always have allocated, if not paused. Only settable for Serverless databases."
Update description to match usual phrasing:

```suggestion
  description = "Minimal capacity that this SQL database will always have allocated if not paused. Value must be greater than 0 is using a SKU in the serverless compute tier."
```

2024-12-20 11:53 UTC, hknutsen commented on modules/database/variables.tf
> +  }
Might be optimistic to maintain a list of all available SKUs:

```suggestion
```

Thoughts?

2024-12-20 12:16 UTC, hknutsen approved these changes, later dismissed

2024-12-20 12:20 UTC, hknutsen approved these changes

2024-12-20 12:25 UTC, helenakallekleiv approved these changes

2024-12-20 12:26 UTC, merged