feat: enable azure ad-only authentication
equinor/terraform-azurerm-sql pull request #42
Opened 2022-10-17 09:54 UTC by helenakallekleiv

Closes #35

2022-10-17 09:56 UTC, helenakallekleiv commented
Tests passed on my local machine.

2022-10-17 12:23 UTC, hknutsen commented
Azure AD authentication only should be optional. Currently it is hardcoded to always be enabled.

You could add a new variable, e.g. `azuread_auth_only`, to enable/disable this feature.

2022-10-17 12:23 UTC, hknutsen requested changes
Azure AD authentication only should be optional. Currently it is hardcoded to always be enabled.

You could add a new variable, e.g. `azuread_auth_only`, to enable/disable this feature.

2022-10-19 08:22 UTC, sebastianlolv approved these changes

2022-10-19 09:19 UTC, hknutsen approved these changes

2022-10-19 11:49 UTC, merged