feat: set server alert policy email attributes
equinor/terraform-azurerm-sql pull request #69
Opened 2023-03-09 10:42 UTC by helenakallekleiv

2023-03-09 10:42 UTC, helenakallekleiv commented
Test pass ⭐

2023-03-09 12:05 UTC, hknutsen requested changes
Looks good 🙂 Added a suggested change to one of the variable descriptions.

2023-03-09 12:05 UTC, hknutsen commented on variables.tf
> +  description = "Is alerts for this SQL server sent to account adminitrators?"
Clarify who receives alerts:

```suggestion
  description = "Are alerts for this SQL server sent to subscription owners and administrators?"
```

2023-03-15 12:02 UTC, hknutsen requested changes
Could also omit `server_` from variable names, since these variables only apply to the server and thus we do not need to specify it.

2023-03-15 12:02 UTC, hknutsen commented on examples/complete/main.tf
> +  server_security_alert_policy_email_addresses      = []
```suggestion
  security_alert_policy_email_account_admins = true
  security_alert_policy_email_addresses      = []
```

2023-03-15 12:02 UTC, hknutsen commented on main.tf
> +  email_account_admins = var.server_security_alert_policy_email_account_admins
```suggestion
  email_addresses      = var.security_alert_policy_email_addresses
  email_account_admins = var.security_alert_policy_email_account_admins
```

2023-03-15 12:02 UTC, hknutsen commented on variables.tf
> +
```suggestion
variable "security_alert_policy_email_addresses" {
  description = "A list of custom email addresses to which the alert for this SQL server is sent."
  type        = list(string)
  default     = []
}

variable "security_alert_policy_email_account_admins" {
  description = "Are alerts for this SQL server sent to subscription owners and administrators?"
  type        = bool
  default     = true
}

```

2023-03-16 09:50 UTC, helenakallekleiv commented
Tests passed 👍🏼

2023-03-16 10:35 UTC, hknutsen approved these changes
Looks good 🎉

2023-03-16 11:11 UTC, merged